// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdates():Promise<main.UpdateInfo>;

export function DismissUpdate(arg1:string):Promise<void>;

export function DownloadUpdate(arg1:string,arg2:string):Promise<main.UpdateInfo>;

export function GetBootstrap(arg1:string):Promise<main.Bootstrap>;

export function OpenDocument(arg1:string):Promise<main.Document>;

export function OpenDownloadedUpdate(arg1:string):Promise<void>;

export function OpenWorkspace():Promise<main.WorkspaceTree>;

export function OpenWorkspaceDocument(arg1:string):Promise<main.Document>;

export function RefreshWorkspace():Promise<main.WorkspaceRefresh>;

export function RestoreWorkspace():Promise<main.WorkspaceTree>;

export function ScanWorkspace(arg1:string):Promise<main.WorkspaceTree>;

export function SearchWorkspace(arg1:string):Promise<Array<main.SearchResult>>;

export function StatDocument(arg1:string,arg2:number,arg3:number):Promise<main.DocumentStatus>;

export function SwitchLanguage(arg1:string):Promise<main.Bootstrap>;

export function SwitchTheme(arg1:string):Promise<main.Bootstrap>;
