// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetBootstrap(arg1:string):Promise<main.Bootstrap>;

export function OpenWorkspace():Promise<main.WorkspaceTree>;

export function ScanWorkspace(arg1:string):Promise<main.WorkspaceTree>;
