// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBootstrap(arg1) {
  return window['go']['main']['App']['GetBootstrap'](arg1);
}

export function OpenDocument(arg1) {
  return window['go']['main']['App']['OpenDocument'](arg1);
}

export function OpenWorkspace() {
  return window['go']['main']['App']['OpenWorkspace']();
}

export function OpenWorkspaceDocument(arg1) {
  return window['go']['main']['App']['OpenWorkspaceDocument'](arg1);
}

export function RestoreWorkspace() {
  return window['go']['main']['App']['RestoreWorkspace']();
}

export function ScanWorkspace(arg1) {
  return window['go']['main']['App']['ScanWorkspace'](arg1);
}

export function SearchWorkspace(arg1) {
  return window['go']['main']['App']['SearchWorkspace'](arg1);
}

export function StatDocument(arg1, arg2, arg3) {
  return window['go']['main']['App']['StatDocument'](arg1, arg2, arg3);
}
