// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddWorkspace(arg1:string):Promise<main.WorkspaceCollection>;

export function CheckForUpdates():Promise<main.UpdateInfo>;

export function ConsumeLaunchRequest():Promise<main.LaunchRequest>;

export function DismissUpdate(arg1:string):Promise<void>;

export function DownloadUpdate(arg1:string,arg2:string):Promise<main.UpdateInfo>;

export function GetBootstrap(arg1:string):Promise<main.Bootstrap>;

export function GetMarkdownAssociationStatus():Promise<main.MarkdownAssociationStatus>;

export function GetReadingMemory():Promise<main.ReadingMemorySnapshot>;

export function GetReadingPosition(arg1:string):Promise<main.ReadingPosition>;

export function GetReadingSession():Promise<main.WorkspaceReadingSession>;

export function LoadDirectory(arg1:string):Promise<main.TreeNode>;

export function OpenDocument(arg1:string):Promise<main.Document>;

export function OpenDownloadedUpdate(arg1:string):Promise<void>;

export function OpenMarkdownDefaultAppsSettings():Promise<void>;

export function OpenWorkspace():Promise<main.WorkspaceCollection>;

export function OpenWorkspaceDocument(arg1:string):Promise<main.Document>;

export function RefreshWorkspace():Promise<main.WorkspaceRefresh>;

export function RefreshWorkspaces():Promise<main.WorkspaceRefresh>;

export function RemoveWorkspace(arg1:string):Promise<main.WorkspaceCollection>;

export function RenamePath(arg1:string,arg2:string):Promise<main.RenameResult>;

export function ReorderWorkspaces(arg1:Array<string>):Promise<main.WorkspaceCollection>;

export function RestoreWorkspace():Promise<main.WorkspaceTree>;

export function RestoreWorkspaces():Promise<main.WorkspaceCollection>;

export function RevealPath(arg1:string):Promise<void>;

export function SaveOpenTabs(arg1:Array<string>,arg2:string):Promise<void>;

export function SaveReadingPosition(arg1:string,arg2:number,arg3:number,arg4:string,arg5:number,arg6:number):Promise<void>;

export function ScanWorkspace(arg1:string):Promise<main.WorkspaceTree>;

export function SearchWorkspace(arg1:string):Promise<Array<main.SearchResult>>;

export function StatDocument(arg1:string,arg2:number,arg3:number):Promise<main.DocumentStatus>;

export function SwitchLanguage(arg1:string):Promise<main.Bootstrap>;

export function SwitchTheme(arg1:string):Promise<main.Bootstrap>;
