// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBootstrap(arg1) {
  return window['go']['main']['App']['GetBootstrap'](arg1);
}

export function OpenDocument(arg1) {
  return window['go']['main']['App']['OpenDocument'](arg1);
}

export function OpenWorkspace() {
  return window['go']['main']['App']['OpenWorkspace']();
}

export function ScanWorkspace(arg1) {
  return window['go']['main']['App']['ScanWorkspace'](arg1);
}
